import { ExportTitlesConfig } from '../types';

export const DEFAULT_EXPORT_TITLES: ExportTitlesConfig = {
  reportMainTitle: 'NYABIHU YEGO CENTER',
  reportSubTitle: 'Youth Services Attendance & Management Report',
  excelRegisterTitle: 'NYABIHU YEGO CENTER - OFFICIAL YOUTH ATTENDANCE REGISTER',
  excelLocationHeader: 'Nyabihu Youth Empowerment for Global Opportunity (YEGO) Center',
  pdfSection1Title: '1. Executive Attendance Summary',
  pdfSection2Title: '2. Service Usage Breakdown',
  pdfSection3Title: '3. What the Attendance Data is Telling You',
  pdfFooterText: 'NYABIHU YEGO CENTER • Official Youth Services Attendance Record System',
  attendanceSheetTitle: 'Attendance Register',
  serviceSummarySheetTitle: 'Service Summary',
  sectorSummarySheetTitle: 'Nyabihu Sectors Breakdown',
  preparedByLabel: 'Generated By',
};

export const EXPORT_TITLES_STORAGE_KEY = 'nyabihu_export_titles_config';

export function loadSavedExportTitles(): ExportTitlesConfig {
  try {
    const saved = localStorage.getItem(EXPORT_TITLES_STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return { ...DEFAULT_EXPORT_TITLES, ...parsed };
    }
  } catch (e) {
    console.warn('Error reading saved export titles config:', e);
  }
  return { ...DEFAULT_EXPORT_TITLES };
}

export function saveExportTitles(config: ExportTitlesConfig): void {
  try {
    localStorage.setItem(EXPORT_TITLES_STORAGE_KEY, JSON.stringify(config));
  } catch (e) {
    console.warn('Error saving export titles config:', e);
  }
}
