import jsPDF from 'jspdf';
import { AttendanceRecord, DashboardStats, PeriodDateRange, UserProfile, ChallengerInsight, ColumnsConfig } from '../types';
import { ALL_COLUMNS, DEFAULT_COLUMNS_CONFIG } from '../constants/columns';

export function exportReportToPDF(
  stats: DashboardStats,
  currentRange: PeriodDateRange,
  userProfile: UserProfile,
  districtName: string,
  insights: ChallengerInsight[],
  filteredRecords: AttendanceRecord[],
  columnsConfig?: ColumnsConfig
) {
  const activeCols = columnsConfig || DEFAULT_COLUMNS_CONFIG;
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = 18;

  // Header background banner
  doc.setFillColor(35, 40, 94); // Navy #23285E
  doc.rect(0, 0, pageWidth, 32, 'F');

  // Accent gold line
  doc.setFillColor(230, 230, 90); // Accent #E6E65A
  doc.rect(0, 32, pageWidth, 2, 'F');

  // Center Name
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('NYABIHU YEGO CENTER', margin, 14);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(223, 248, 245); // Light blue tint
  doc.text('Youth Services Attendance & Management Report', margin, 21);

  // District badge in top right
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(`District: ${districtName.toUpperCase()}`, pageWidth - margin, 14, { align: 'right' });

  const generatedDateStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Generated: ${generatedDateStr}`, pageWidth - margin, 21, { align: 'right' });

  y = 42;

  // Report metadata box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 22, 2, 2, 'FD');

  doc.setTextColor(31, 34, 44);
  doc.setFontSize(9);

  // Row 1
  doc.setFont('helvetica', 'bold');
  doc.text('Reporting Period:', margin + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.text(`${currentRange.label} (${currentRange.startDate} to ${currentRange.endDate})`, margin + 36, y + 7);

  // Row 2
  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', margin + 4, y + 15);
  doc.setFont('helvetica', 'normal');
  doc.text(`${userProfile.fullName} (${userProfile.role === 'director' ? 'Main Director' : 'District Administrator'})`, margin + 36, y + 15);

  y += 28;

  // Summary Metrics Section Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(35, 40, 94);
  doc.text('1. Executive Attendance Summary', margin, y);
  y += 6;

  // 4 Metric cards
  const cardWidth = (pageWidth - margin * 2 - 9) / 4;
  const metrics = [
    { label: 'Total Visits', val: stats.filteredTotal.toLocaleString(), sub: `${stats.dailyAverage}/day avg` },
    { label: 'Male Visits', val: stats.maleTotal.toLocaleString(), sub: `${stats.malePercentage}% share` },
    { label: 'Female Visits', val: stats.femaleTotal.toLocaleString(), sub: `${stats.femalePercentage}% share` },
    { label: 'Top Service', val: stats.mostRequestedService ? stats.mostRequestedService.totalCount.toString() : '0', sub: stats.mostRequestedService ? stats.mostRequestedService.serviceName.substring(0, 14) + '...' : 'N/A' },
  ];

  metrics.forEach((m, idx) => {
    const cx = margin + idx * (cardWidth + 3);
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(cx, y, cardWidth, 20, 2, 2, 'FD');

    // Accent top bar
    doc.setFillColor(53, 145, 200);
    doc.rect(cx, y, cardWidth, 1.5, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(m.label, cx + cardWidth / 2, y + 6, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(35, 40, 94);
    doc.text(m.val, cx + cardWidth / 2, y + 12, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(m.sub, cx + cardWidth / 2, y + 17, { align: 'center' });
  });

  y += 26;

  // Section 2: Service Breakdown Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(35, 40, 94);
  doc.text('2. Service Usage Breakdown', margin, y);
  y += 6;

  // Table header
  const thHeight = 7;
  doc.setFillColor(35, 40, 94);
  doc.rect(margin, y, pageWidth - margin * 2, thHeight, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text('Service Name', margin + 4, y + 5);
  doc.text('Male', margin + 95, y + 5, { align: 'right' });
  doc.text('Female', margin + 120, y + 5, { align: 'right' });
  doc.text('Total Visits', margin + 150, y + 5, { align: 'right' });
  doc.text('Share (%)', pageWidth - margin - 4, y + 5, { align: 'right' });
  y += thHeight;

  // Table rows
  doc.setFontSize(8);
  stats.serviceBreakdown.forEach((srv, index) => {
    const isEven = index % 2 === 0;
    doc.setFillColor(isEven ? 255 : 248, isEven ? 255 : 250, isEven ? 255 : 252);
    doc.rect(margin, y, pageWidth - margin * 2, 6.5, 'F');
    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 6.5, pageWidth - margin, y + 6.5);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(31, 34, 44);
    const truncName = srv.serviceName.length > 44 ? srv.serviceName.substring(0, 42) + '...' : srv.serviceName;
    doc.text(truncName, margin + 4, y + 4.5);

    doc.text(srv.maleCount.toString(), margin + 95, y + 4.5, { align: 'right' });
    doc.text(srv.femaleCount.toString(), margin + 120, y + 4.5, { align: 'right' });

    doc.setFont('helvetica', 'bold');
    doc.text(srv.totalCount.toString(), margin + 150, y + 4.5, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.text(`${srv.percentage}%`, pageWidth - margin - 4, y + 4.5, { align: 'right' });

    y += 6.5;
  });

  // Total row
  doc.setFillColor(223, 248, 245);
  doc.rect(margin, y, pageWidth - margin * 2, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(35, 40, 94);
  doc.text('Total Service Attendance', margin + 4, y + 5);
  doc.text(stats.maleTotal.toString(), margin + 95, y + 5, { align: 'right' });
  doc.text(stats.femaleTotal.toString(), margin + 120, y + 5, { align: 'right' });
  doc.text(stats.filteredTotal.toString(), margin + 150, y + 5, { align: 'right' });
  doc.text('100.0%', pageWidth - margin - 4, y + 5, { align: 'right' });

  y += 14;

  // Section 3: Data Insights & Observations
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(35, 40, 94);
  doc.text('3. What the Attendance Data is Telling You', margin, y);
  y += 6;

  insights.slice(0, 3).forEach((ins) => {
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, y, pageWidth - margin * 2, 14, 1.5, 1.5, 'FD');

    // Left accent bar
    doc.setFillColor(ins.type === 'attention' ? 220 : 53, ins.type === 'attention' ? 38 : 145, ins.type === 'attention' ? 38 : 200);
    doc.rect(margin, y, 2.5, 14, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(35, 40, 94);
    doc.text(ins.headline, margin + 5, y + 5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(71, 85, 105);
    const obsTrunc = ins.observation.length > 110 ? ins.observation.substring(0, 108) + '...' : ins.observation;
    doc.text(obsTrunc, margin + 5, y + 10);

    y += 16;
  });

  // Footer on page 1
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, 280, pageWidth - margin, 280);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text('NYABIHU YEGO CENTER • Official Youth Services Attendance Record System', margin, 285);
  doc.text('Page 1 of 1', pageWidth - margin, 285, { align: 'right' });

  // Save the PDF
  const filename = `Nyabihu_Yego_Report_${districtName.replace(/\s+/g, '_')}_${currentRange.startDate}_${currentRange.endDate}.pdf`;
  doc.save(filename);
}
